import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

const kperson = Icons.person;
const ksecurity = Icons.lock;
const khide = Icons.visibility_off;
const kshow = Icons.visibility;
const ksqGrid = CupertinoIcons.square_grid_2x2_fill;
const ksearchicon = CupertinoIcons.search;
const kmorevert = Icons.more_vert_rounded;
const kadd = Icons.add;
const kremove = Icons.remove;
const kcart = Icons.shopping_cart;
const kback = CupertinoIcons.back;
const kfavorite_outline = Icons.favorite_outline_outlined;
const kfavorite = Icons.favorite;
const kclose = Icons.close;
const kadd_box = Icons.add_box_outlined;
const kdrawer = Icons.menu;
const kaddAccount = Icons.person_add;
const kcomment = CupertinoIcons.chat_bubble;
const kshare = Icons.send;
const kcollection = Icons.collections_outlined;
const kmessage = CupertinoIcons.bolt_horizontal_circle;
const ksave = CupertinoIcons.bookmark;
const kgrid = Icons.grid_on_outlined;
const kcheck = Icons.check;
